export enum WsEvent {
  // Client -> Server
  HOST_CHANGE_SCENE = 'HOST_CHANGE_SCENE',
  USER_SHAKE_ACTION = 'USER_SHAKE_ACTION',
  JOIN_ROOM = 'JOIN_ROOM',
  JOIN_MATCH_ROOM = 'JOIN_MATCH_ROOM',
  HOST_HEARTBEAT = 'HOST_HEARTBEAT',
  MATCH_ACCEPT = 'MATCH_ACCEPT',
  MATCH_REJECT = 'MATCH_REJECT',
  MATCH_BLIND_CHAT = 'MATCH_BLIND_CHAT',

  // Server -> All Clients
  SCENE_UPDATED = 'SCENE_UPDATED',
  LOTTERY_WINNER_ANNOUNCE = 'LOTTERY_WINNER_ANNOUNCE',
  ICEBREAKER_QUESTION = 'ICEBREAKER_QUESTION',
  ICEBREAKER_CLOSED = 'ICEBREAKER_CLOSED',
  HOST_CHANGED = 'HOST_CHANGED',
  MATCH_RESULT = 'MATCH_RESULT',

  // Server -> Big Screen
  USER_CHECKED_IN = 'USER_CHECKED_IN',
  SHAKE_LEADERBOARD_TICK = 'SHAKE_LEADERBOARD_TICK',
  SHAKE_STARTED = 'SHAKE_STARTED',
  SHAKE_ENDED = 'SHAKE_ENDED',
  STAR_LIT_UP = 'STAR_LIT_UP',
  MATCH_LINES = 'MATCH_LINES',

  // Server -> User (per-user delivery, NOT 大屏广播)
  // 用户自己作答后收到，可用于震动/动效反馈
  ICEBREAKER_ANSWERED = 'ICEBREAKER_ANSWERED',
  LOTTERY_WON = 'LOTTERY_WON',

  // v2.0 体验流（Experience Stream）
  // 一次推送携带完整 stream（current + queue + history + suggestions）
  // 前端用一次 update 替代多次 WS 事件处理
  STREAM_UPDATED = 'STREAM_UPDATED',
  SUGGESTIONS_UPDATED = 'SUGGESTIONS_UPDATED',
}
