// ⚠️ 警告：与后端 backend/src/common/enums/event-status.enum.ts 和 ws-event.enum.ts 保持同步
// 修改时请同时更新三处。后端为权威源。

export enum WsEvent {
  HOST_CHANGE_SCENE = 'HOST_CHANGE_SCENE',
  USER_SHAKE_ACTION = 'USER_SHAKE_ACTION',
  JOIN_ROOM = 'JOIN_ROOM',
  JOIN_MATCH_ROOM = 'JOIN_MATCH_ROOM',
  HOST_HEARTBEAT = 'HOST_HEARTBEAT',
  SCENE_UPDATED = 'SCENE_UPDATED',
  LOTTERY_WINNER_ANNOUNCE = 'LOTTERY_WINNER_ANNOUNCE',
  USER_CHECKED_IN = 'USER_CHECKED_IN',
  SHAKE_LEADERBOARD_TICK = 'SHAKE_LEADERBOARD_TICK',
  SHAKE_STARTED = 'SHAKE_STARTED',
  SHAKE_ENDED = 'SHAKE_ENDED',
  ICEBREAKER_QUESTION = 'ICEBREAKER_QUESTION',
  ICEBREAKER_CLOSED = 'ICEBREAKER_CLOSED',
  HOST_CHANGED = 'HOST_CHANGED',
  STAR_LIT_UP = 'STAR_LIT_UP',
  MATCH_RESULT = 'MATCH_RESULT',
  MATCH_ACCEPT = 'MATCH_ACCEPT',
  MATCH_REJECT = 'MATCH_REJECT',
  MATCH_BLIND_CHAT = 'MATCH_BLIND_CHAT',

  // Per-user events (server -> single user)
  ICEBREAKER_ANSWERED = 'ICEBREAKER_ANSWERED',
  LOTTERY_WON = 'LOTTERY_WON',
}

export enum EventStatus {
  STANDBY = 'STATUS_STANDBY',
  CHECKIN = 'STATUS_CHECKIN',
  ICEBREAKER = 'STATUS_ICEBREAKER',
  LOTTERY_READY = 'STATUS_LOTTERY_READY',
  LOTTERY_RUNNING = 'STATUS_LOTTERY_RUNNING',
  GAME_SHAKE = 'STATUS_GAME_SHAKE',
  GAME_MATCH = 'STATUS_GAME_MATCH',
  ENDED = 'STATUS_ENDED',
}
