// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/8/2026, 10:50:32 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/liyijia/Create/FlashMeet/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liyijia/Create/FlashMeet/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liyijia/Create/FlashMeet/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liyijia/Create/FlashMeet/website/plugins/**/*.{js,ts,mjs}","/Users/liyijia/Create/FlashMeet/website/composables/**/*.{js,ts,mjs}","/Users/liyijia/Create/FlashMeet/website/utils/**/*.{js,ts,mjs}","/Users/liyijia/Create/FlashMeet/website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liyijia/Create/FlashMeet/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/liyijia/Create/FlashMeet/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/liyijia/Create/FlashMeet/website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;