// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/21 09:41:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["E:/Test/FlashMeet/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Test/FlashMeet/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Test/FlashMeet/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Test/FlashMeet/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Test/FlashMeet/website/plugins/**/*.{js,ts,mjs}","E:/Test/FlashMeet/website/composables/**/*.{js,ts,mjs}","E:/Test/FlashMeet/website/utils/**/*.{js,ts,mjs}","E:/Test/FlashMeet/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Test/FlashMeet/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Test/FlashMeet/website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;